import { CommonModule } from '@angular/common';
import { Component, HostListener, OnInit, inject } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { finalize } from 'rxjs';
import { SalesTeamOnboardingService } from '../../services/sales-team-onboarding.service';
import { ClientUserVerificationService, CommissionPlanOption, UserDropdownOption } from '../../services/client-user-verification.service';
import { NgSelectModule } from '@ng-select/ng-select';

type DocType='PanCopy'|'AadhaarFront'|'AadhaarBack'|'Selfie'|'Logo';
@Component({selector:'app-sales-team-onboarding',standalone:true,imports:[CommonModule,ReactiveFormsModule,FormsModule,NgSelectModule],templateUrl:'./sales-team-onboarding.component.html',styleUrl:'./sales-team-onboarding.component.scss'})
export class SalesTeamOnboardingComponent implements OnInit{
 private fb=inject(FormBuilder);private api=inject(SalesTeamOnboardingService);private lookups=inject(ClientUserVerificationService);private route=inject(ActivatedRoute);private router=inject(Router);
 userId=0;rowVersion='';status='Draft';saving=false;message='';error='';step=1;documents:any[]=[];history:any[]=[];verified:any={phone:false,email:false,pan:false,aadhaar:false};readonly docTypes:DocType[]=['PanCopy','AadhaarFront','AadhaarBack','Selfie','Logo'];
 dialog:''|'otp'|'correction'|'submit'|'leave'='';dialogTitle='';dialogText='';dialogValue='';otpType:'phone'|'email'='phone';challengeId='';pendingFile?:File;pendingDoc?:DocType;initializing=true;
 readonly mandatory=['userType','companyName','name','fatherName','username','emailId','phone','panCard','aadharCard','addressLine1','state','city','pincode','shopAddress','shopState','shopCity','shopZipCode','latitude','longitude','commissionPlanId'] as const;
 commissionPlans:CommissionPlanOption[]=[];wlUsers:UserDropdownOption[]=[];
 form=this.fb.group({userType:['RT',Validators.required],companyName:[''],name:[''],fatherName:[''],username:[''],emailId:['',Validators.email],phone:['',[Validators.pattern(/^[6-9]\d{9}$/)]],panCard:['',[Validators.pattern(/^[A-Z]{5}\d{4}[A-Z]$/)]],aadharCard:['',[Validators.pattern(/^\d{12}$/)]],addressLine1:[''],addressLine2:[''],state:[''],city:[''],pincode:['',[Validators.pattern(/^\d{6}$/)]],shopAddress:[''],shopState:[''],shopCity:[''],shopZipCode:['',[Validators.pattern(/^\d{6}$/)]],latitude:['',[Validators.pattern(/^-?\d{1,2}(\.\d{1,4})?$/)]],longitude:['',[Validators.pattern(/^-?\d{1,3}(\.\d{1,4})?$/)]],wlId:[{value:null as number|null,disabled:true}],commissionPlanId:[null as number|null]});
 ngOnInit(){this.lookups.getCommissionPlans().subscribe(r=>this.commissionPlans=r.data||[]);this.api.hierarchyContext().subscribe({next:r=>{const mapped=r.data;this.wlUsers=[mapped];if(!this.userId)this.form.controls.wlId.setValue(mapped.id,{emitEvent:false});},error:e=>this.error=e.error?.message||'Unable to load your mapped White Label user.'});const id=Number(this.route.snapshot.paramMap.get('id'));if(id)this.load(id);else setTimeout(()=>this.initializing=false);}
 load(id:number){this.saving=true;this.api.detail(id).pipe(finalize(()=>this.saving=false)).subscribe({next:r=>this.apply(r.data),error:e=>this.error=e.error?.message||'Unable to load onboarding.'});}
 findByPhone(){const phone=this.form.controls.phone.value||'';if(!/^\d{10}$/.test(phone)){this.error='Enter a valid phone number.';return;}this.saving=true;this.api.resume(phone).pipe(finalize(()=>this.saving=false)).subscribe({next:r=>r.data?this.apply(r.data):this.message='No editable draft found. You can start a new onboarding.',error:e=>this.error=e.error?.message||'Search failed.'});}
 saveDraft(next=false){if(this.form.invalid){this.form.markAllAsTouched();this.error='Correct highlighted field formats.';return;}this.saving=true;this.error='';this.api.saveDraft({...this.form.getRawValue(),userId:this.userId,rowVersion:this.rowVersion}).pipe(finalize(()=>this.saving=false)).subscribe({next:r=>{this.userId=r.data.userId;this.rowVersion=r.data.rowVersion;this.status=r.data.onboardingStatus;this.form.markAsPristine();this.message='Draft saved securely.';if(next)this.step=Math.min(3,this.step+1);},error:e=>this.error=e.error?.message||'Draft could not be saved.'});}
 fileSelected(type:DocType,event:Event){const file=(event.target as HTMLInputElement).files?.[0];if(!file||!this.userId){this.error='Save the draft before uploading documents.';return;}this.pendingFile=file;this.pendingDoc=type;const existing=this.documents.find(d=>d.documentType===type);if(existing?.reviewStatus==='Rejected'){this.openDialog('correction','Correction remarks',`Explain what was corrected in ${type}.`);return;}this.uploadPending('');}
 private uploadPending(remarks:string){if(!this.pendingFile||!this.pendingDoc)return;this.saving=true;this.api.uploadDocument(this.userId,this.pendingDoc,this.pendingFile,remarks).pipe(finalize(()=>this.saving=false)).subscribe({next:()=>{this.message=`${this.pendingDoc} uploaded.`;this.closeDialog();this.load(this.userId);},error:e=>this.error=e.error?.message||'Upload failed.'});}
 submit(){const missing=this.mandatory.filter(k=>!String(this.form.controls[k].value??'').trim());if(missing.length){this.form.markAllAsTouched();this.error='Complete all mandatory identity, address, location and commission-plan fields.';this.step=missing.some(x=>['addressLine1','state','city','pincode','shopAddress','shopState','shopCity','shopZipCode','latitude','longitude'].includes(x))?2:1;return;}if(!this.userId){this.error='Save the draft first.';return;}if(this.form.dirty){this.error='Save your latest changes before submitting.';return;}this.openDialog('submit','Submit onboarding','This application will be locked and sent to SuperAdmin for review.');}
 private performSubmit(){this.saving=true;this.api.submit(this.userId,this.rowVersion).pipe(finalize(()=>this.saving=false)).subscribe({next:r=>{this.form.markAsPristine();this.closeDialog();this.message=r.data.message;void this.router.navigate(['/sales-team/dashboard']);},error:e=>{this.closeDialog();this.error=e.error?.message||'Submission failed.';}});}
 verifyOtp(type:'phone'|'email'){if(!this.userId){this.error='Save the draft before verification.';return;}if(this.form.dirty){this.error='Save changed contact details before verification.';return;}const value=type==='phone'?this.form.controls.phone.value:this.form.controls.emailId.value;if(!value){this.error=`Enter ${type} first.`;return;}this.saving=true;this.api.sendOtp(type,value,this.userId).pipe(finalize(()=>this.saving=false)).subscribe({next:r=>{if(!r.success){this.error=r.message;return;}this.otpType=type;this.challengeId=r.challengeId;this.openDialog('otp',`${type==='phone'?'Phone':'Email'} verification`,`Enter the 6-digit OTP sent to ${value}.`);},error:e=>this.error=e.error?.message||'OTP could not be sent.'});}
 verifyIdentity(type:'pan'|'aadhaar'){if(!this.userId){this.error='Save the draft before verification.';return;}if(this.form.dirty){this.error='Save changed identity details before verification.';return;}const value=type==='pan'?this.form.controls.panCard.value:this.form.controls.aadharCard.value;if(!value){this.error=`Enter ${type.toUpperCase()} first.`;return;}this.saving=true;const call=type==='pan'?this.api.verifyPan(value,this.userId):this.api.verifyAadhaar(value,this.userId);call.pipe(finalize(()=>this.saving=false)).subscribe({next:r=>{if(r.success){this.message=`${type.toUpperCase()} verified${r.verifiedName?' for '+r.verifiedName:''}.`;this.load(this.userId);}else this.error=r.message;},error:e=>this.error=e.error?.message||`${type.toUpperCase()} verification failed.`});}
 verifyDialogOtp(){if(!/^\d{6}$/.test(this.dialogValue.trim())){this.error='Enter a valid 6-digit OTP.';return;}this.saving=true;this.api.verifyOtp(this.challengeId,this.dialogValue.trim(),this.otpType,this.userId).pipe(finalize(()=>this.saving=false)).subscribe({next:v=>{if(v.success){this.message=`${this.otpType==='phone'?'Phone':'Email'} verified.`;this.closeDialog();this.load(this.userId);}else this.error=v.message;},error:e=>this.error=e.error?.message||'OTP verification failed.'});}
 openDialog(type:'otp'|'correction'|'submit'|'leave',title:string,text:string){this.dialog=type;this.dialogTitle=title;this.dialogText=text;this.dialogValue='';}
 closeDialog(){this.dialog='';this.dialogValue='';this.pendingFile=undefined;this.pendingDoc=undefined;}
 confirmDialog(){if(this.dialog==='otp')this.verifyDialogOtp();else if(this.dialog==='correction'){if(this.dialogValue.trim().length<3){this.error='Correction remarks are mandatory.';return;}this.uploadPending(this.dialogValue.trim());}else if(this.dialog==='submit')this.performSubmit();else if(this.dialog==='leave'){this.form.markAsPristine();void this.router.navigate(['/sales-team/dashboard']);}}
 goDashboard(){if(this.form.dirty)this.openDialog('leave','Discard unsaved changes?','Your latest changes have not been saved.');else void this.router.navigate(['/sales-team/dashboard']);}
 viewDocument(doc:any,versionId?:number){const call=versionId?this.api.documentVersion(this.userId,versionId):this.api.document(this.userId,doc.id);this.saving=true;call.pipe(finalize(()=>this.saving=false)).subscribe({next:blob=>{const url=URL.createObjectURL(blob);window.open(url,'_blank','noopener');setTimeout(()=>URL.revokeObjectURL(url),60000);},error:e=>this.error=e.error?.message||'Document could not be opened.'});}
 private apply(d:any){this.initializing=true;this.userId=d.userId;this.rowVersion=d.rowVersion;this.status=d.onboardingStatus;this.documents=d.documents||[];this.history=d.history||[];this.verified={phone:!!d.isPhoneVerified,email:!!d.isEmailVerified,pan:!!d.isPanVerified,aadhaar:!!d.isAadhaarVerified};this.form.enable({emitEvent:false});this.form.patchValue({...d,wlId:Number(d.wlId)||null});this.form.controls.wlId.disable({emitEvent:false});if(d.aadhaarMasked)this.form.controls.aadharCard.setValue('');if(!this.canEdit)this.form.disable({emitEvent:false});this.form.markAsPristine();setTimeout(()=>this.initializing=false);if(d.finalReviewRemarks)this.message=`SuperAdmin final remarks: ${d.finalReviewRemarks}`;}
 get canEdit(){return this.status==='Draft'||this.status==='Rejected';}
 @HostListener('window:beforeunload',['$event']) beforeUnload(e:BeforeUnloadEvent){if(this.form.dirty){e.preventDefault();e.returnValue='';}}
 doc(type:DocType){return this.documents.find(d=>d.documentType===type);}
}
